# Generated by Django 4.1.2 on 2022-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.CharField(default='nada-com-nada', max_length=200),
            preserve_default=False,
        ),
    ]
