# Generated by Django 4.1.2 on 2022-11-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='content',
        ),
    ]
