# Generated by Django 4.1.2 on 2022-11-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_rating_game_ratingqty_game_rawgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ratingQty',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rawgID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
